modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="http://hycrafthd.net"
displayURL="http://hycrafthd.net"
authors="HyCraftHD"

[[mods]]
	modId="tutorialmod"
	version="${file.jarVersion}"
	displayName="Tutorial Mod"
	description='''
		Tutorial Mod
	'''
	
	[[dependencies.tutorialmod]]
	    modId="forge"
	    mandatory=true
	    versionRange="[25.0.108,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.tutorialmod]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.13.2]"
	    ordering="NONE"
	    side="BOTH"